### ISSUE TITLE
Crash when opening program

### ISSUE THREAD

**Issue by agiz10** [Nagru/Manga-Organizer#10]
When i try to open program with last few versions of MO, i get this error. Windows 7 x64 here.
Help?

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: 'count' must be non-negative.
Parameter name: count
   at System.String.CtorCharCount(Char c, Int32 count)
   at Nagru___Manga_Organizer.Ext.RatingFormat(Int32 iRating)
   at Nagru___Manga_Organizer.Main.UpdateLV()
   at Nagru___Manga_Organizer.Main.Database_Display()
```

**Comment by Nagru** [comment]
Based on the timing, it seems you have a rating of more than 5 stars for a manga. I'll take a look into how that could have happened. Please try out the latest version though, it's been updated to force out-of-range ratings into a useable value.

**Comment by agiz10** [comment]
Works. Thank you :)
