### ISSUE TITLE
Crashing sometimes after adding an entry. 

### ISSUE THREAD

**Issue by Phooh** [Nagru/Manga-Organizer#12]
I think this bug originated from 4.8.56 or back. Whenever I add an entry(drag and drop to the Brows tab) MO would crash if I don't add the URL first. If I try to add the tags before the URL MO would crash(I drag and drop the tags, I haven't tried just typing them in). In some cases I also noticed the font of the entry's Title would change once added. I can't seem to remember which entries did this so I can't give more details on this.

Really though just about anything would make MO crash after adding the entry. The URL thing is just happens more common. Sometimes it'll crash even if I do add the URL first.

**Comment by Nagru** [comment]
It specifically has something to do with drag/dropping text longer than the control and then trying to update the scrollbar state. I'm not sure exactly what yet so I've simply uploaded a new version that removes the SetScroll call in that scenario.

**Comment by Nagru** [comment]
Finally found a way around the issue by calling BeginInvoke() in that context. Will use for the rest of the week and then upload if no issues crop up.
