### ISSUE TITLE
Built-in image viewer only opens on main monitor

### ISSUE THREAD

**Issue by Bozunee** [Nagru/Manga-Organizer#16]
Small issue as it was a feature removed with an update, previous to the current version (4.8.95) the image viewer would open in full screen on the monitor it was located at.
Hoping this could be brought back or some option to enable it again.

**Comment by Nagru** [comment]
Oh! Thanks for letting me know.

I've added some code to bring that functionality back. If the main window's edge is within 2-3px of the screen's edge it may open on the opposite screen though. Will look into improving that.

**Comment by Bozunee** [comment]
Awesome, updated and functions correctly.
On the side note I found the image browser doesn't like a different sized monitor than the main.
I'm using an old 4:3 monitor as a third for the sake of saving money and the image browser stays oriented with the main monitor is seems.
Just a minor issue that I just found.
Screenshot for simplicity.
![moexample](https://cloud.githubusercontent.com/assets/14995540/10334505/a1fcc22e-6cb8-11e5-8869-0271676fc8b3.jpg)

**Comment by Nagru** [comment]
Problem with this issue is that I don't have a good way to test a fix for it.

Would you mind being a guinea pig once I write some code to address it?

**Comment by Bozunee** [comment]
I can easily test it out with my two different sized monitors.
I also have my laptop that I can connect with other size screens like a TV, so I can do that as well.

**Comment by Nagru** [comment]
Would you try this out:
<a href="https://cloud.openmailbox.org/index.php/s/cZV3ryNTfAXWEU3">https://cloud.openmailbox.org/index.php/s/cZV3ryNTfAXWEU3</a>

Just replaced FormWindowState.Maximized with Screen.GetBounds(). Curious if there'll be a behavioral difference.

**Comment by Bozunee** [comment]
It adjusted to my 4:3 monitor and fit within the edges of the screen.
Looks like it works between all my monitors. Seems like you found a solution.

**Comment by Nagru** [comment]
Sweet; thanks for testing it.
