### ISSUE TITLE
Certain  characters make MO a bit screwy

### ISSUE THREAD

**Issue by Phooh** [Nagru/Manga-Organizer#17]
I want to start off by mentioning that the font changing issue was still happening for me from my previous topic https://github.com/Nagru/Manga-Organizer/issues/12. I found out what was going on. Basically whenever there was a special character(?  |  / \ : < > ") anywhere in the name of the folder I was adding, the font would change to, what I'm guessing is MS Serif. Normally in Windows you(or atleast me) can't make certain files with certain characters in the name(?  |  / \ : < > "). What I've been doing lately was converting my doujins into .cbz, so I was able to get away with useing those special characters and that's why the font would change when trying to read my .cbz files. This pic is whats been happing for me. http://i.imgur.com/9Yo2rrB.jpg   I don't know if I'd call it a bug or even if it needs fixing. I just thought you'd like to know.  

However, there is still some problems I'm having with the name of certain doujins having other special characters. I think this started in 4.8.95. Its kind of hard for me to describe but, doujins that have the following, is what I'm guessing multiable periods, commas, dashes(maybe?) throw MO way off. If you try to rename the original default MO artist name of a doujin with these special characters and add a similar doujin with special characters from before, MO renames the previous one or ones into a new badly ordered artist name. Maybe too many periods in one tag, I don't know. This was kind of hard for me to recreate(and explain) just to get a clue as to what's going on but here's an example. Oh also I'm not using .cbz for this, I tried with normal empty folders and got the same results.

http://exhentai.org/g/615607/8e7419d07d/

MO hates just about anything to do with this artist/group. At first it seems fine but add these(same group/artist) and try to renaming each artist name in the View Tab. 

http://exhentai.org/g/296835/d7b4131b60/
http://exhentai.org/g/791495/b155aae9ef/ 
http://exhentai.org/g/592089/bf79c4a549/

If nothing still happens just try adding more from (St. Armadel Ch.) or (Kagetora). Its why I say its hard for me to recreate. Sometimes it'll even ignore whatever the Browse Tab saids and continue to use the badly ordered artist name in the View Tab. I haven't been able to recreate this yet in 4.9.00. Sorry if this seems vauge, it was the best way I could describe this.

**Comment by Nagru** [comment]
There was an update a while ago to separate comma-delimited artists into individual records for the database. What it didn't account for is the Group info being left in the Artist field, so the code ends up thinking "<i>St. Armadel Ch. (Kagetora</i>" is an Artist. I'll update the gallery title parsing code to strip that info out.

I am aware of the font changing but it doesn't bother me. Might come back to it later but would prefer to finish Shadow Warrior first.

**Comment by Nagru** [comment]
New code's in place as version 4.9.02

Also comes with an update to ensure blank Artists/Tags don't get created in the database.

**Comment by Phooh** [comment]
I see. Thanks man, you are the organizing hero we deserve!
