### ISSUE TITLE
Filenames are only read up to the first dot in them

### ISSUE THREAD

**Issue by bem13** [Nagru/Manga-Organizer#7]
As an example: I have a folder called "[Saida Kazuaki] Paipain Ch. 1-8 Complete (English) [Brolen & Makasu]". When using the Scan function, the program determines the title as "[Paipain Ch](http://i.imgur.com/bgUZ7BU.jpg)" and that's it. This happens with any folder which has a dot in its name. Of course, you can fix it manually later, but it's still a bit annoying.

Edit: I just noticed that dots also break the search. [With dot](http://i.imgur.com/iKaKg6C.jpg) | [Without dot](http://i.imgur.com/mdcP7Rd.jpg)

**Comment by Nagru** [comment]
Thanks for letting me know.

The first issue was a simple fix to treat folders differently from files when parsing the name. That'll be deployed in the next day or two. The second issue is rather odd; don't know off-the-cuff what the issue might be but I'll take a look later today.

**Comment by Nagru** [comment]
Looks like you stumbled across a feature of EH not covered on their wiki.

From a little testing it seems that periods are treated by the search engine as a sort of 'non-breaking space'. So a search for <a href="http://exhentai.org/?f_doujinshi=1&f_manga=1&f_search=A.Witch.in.Love&f_apply=Apply+Filter">A.Witch.in.Love</a> is functionally equivalent to a search for <a href="http://exhentai.org/?f_doujinshi=1&f_manga=1&f_search=%22A+Witch+in+Love%22&f_apply=Apply+Filter">"A Witch in Love"</a> (note the quotation marks).

Also, for examples of quirkiness as a combination of periods and EH removing too short search terms:
<a href="http://exhentai.org/?f_doujinshi=1&f_manga=1&f_search=paipain+ch.+1-8&f_apply=Apply+Filter">Paipain ch. 1-8</a> (No results)
<a href="http://exhentai.org/?f_doujinshi=1&f_manga=1&f_search=paipain+ch+1-8&f_apply=Apply+Filter">Paipain ch 1-8</a> (Too many results)
<a href="http://exhentai.org/?f_doujinshi=1&f_manga=1&f_search=paipain+ch1-8&f_apply=Apply+Filter">Paipain ch1-8</a> (Perfect)
<a href="http://exhentai.org/?f_doujinshi=1&f_manga=1&f_search=%22paipain+ch.+1-8%22&f_apply=Apply+Filter">"Paipain ch. 1-8"</a> (Also perfect)

I'm going to leave things as they are on my end; it'd be silly to code around how Tenboro has things running.

**Comment by bem13** [comment]
Interesting. Yeah, it makes sense to leave it the way it is.

Thanks for your help!
